<?php

namespace App\Controllers;

use App\Auth;
use App\Controllers\Authenticated;
use Core\View;
use Cloudinary\Api\Upload\UploadApi;
use Cloudinary\Configuration\Configuration;

class Admin extends Authenticated {
    public function index() {
        View::renderTemplate('Admin/index.twig');
    }

    public function bookIndex() {
        View::renderTemplate('Admin/books/index.twig');
    }

    public function bookDetail() {
        View::renderTemplate('Admin/books/edit.twig');
    }

    public function bookCreate() {
        View::renderTemplate('Admin/books/create.twig');
    }

    public function bookCreateNew() {
        Configuration::instance(['cloud' => ['cloud_name' => 'dspnu4m0h', 'api_key' => '741638477628395', 'api_secret' => '8jZMZlNV8n-KoOabOP7O9A08rkw'], 'url' => ['secure' => true]]);
        (new UploadApi())->upload($_POST['book_pages'][0]);
    }

    protected function before() {
        parent::before(); // TODO: Change the autogenerated stub
        $this->user = Auth::getUser();
    }
}