<?php

namespace App\Controllers;

use App\Auth;
use App\Models\Book;
use App\Models\BookDetails;
use Core\View;

class Admin extends Authenticated {
    public function index() {
        View::renderTemplate('Admin/index.twig');
    }

    public function bookIndex() {
        $books = Book::findAll();
        View::renderTemplate('Admin/books/index.twig', ['books' => $books]);
    }

    public function bookDetail() {
        View::renderTemplate('Admin/books/edit.twig');
    }

    public function bookCreate() {
        View::renderTemplate('Admin/books/create.twig');
    }

    public function bookCreateNew() {
        $bookId = Book::insertBook($_POST);
        BookDetails::insertBookDetail($bookId, $_POST['page_link']);
        $this->redirect('/admin/books');
    }

    protected function before() {
        parent::before(); // TODO: Change the autogenerated stub
        $this->user = Auth::getUser();
    }
}